# Generated by Django 5.2.5 on 2025-09-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
