# Generated by Django 5.2.5 on 2025-09-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_jobseeker_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
