# Generated by Django 5.2.5 on 2025-09-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_jobseeker_city_jobseeker_country_jobseeker_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='state',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='userLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='jobseeker.jobseeker')),
            ],
        ),
        migrations.DeleteModel(
            name='userLink',
        ),
    ]
