# Generated by Django 5.2.5 on 2025-09-16 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_remove_jobseeker_city_remove_jobseeker_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='jobseeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='jobseeker.jobseeker'),
        ),
        migrations.CreateModel(
            name='userLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='jobseeker.jobseeker')),
            ],
        ),
    ]
