# Generated by Django 5.2.5 on 2025-09-16 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_alter_userlocation_jobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='jobseeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='jobseeker.jobseeker'),
        ),
    ]
