# Generated by Django 5.2.5 on 2025-09-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_alter_userlocation_jobseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='urls',
        ),
    ]
