# Generated by Django 5.2.5 on 2025-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_skill_jobseeker_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
