# Generated by Django 5.2.5 on 2025-09-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0010_userlocation_latitude_userlocation_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='lastName',
        ),
    ]
