# Generated by Django 5.2.6 on 2025-09-20 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_delete_skill_alter_job_skills'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiter.recruiter'),
        ),
    ]
