# Generated by Django 5.2.6 on 2025-09-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblocation',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblocation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
